# Extra autostart processes
# exec-once = uwsm-app -- my-service
exec = ~/.config/omarchy/scripts/clamshell.sh check
exec = pgrep -f "\.config/omarchy/scripts/clamshell-events\.sh" >/dev/null || ~/.config/omarchy/scripts/clamshell-events.sh
