[theme.templates]
enable_builtin_templates = true
builtin_ids = ["niri"]

[plugins]
enabled = ["dominik/battery-threshold"]

[[plugins.source]]
name = "local-developer"
kind = "path"
location = "~/Developer"
