[mgr]
prepend_keymap = [
	{ on = [ "g", "h" ], run = "cd ~",           desc = "Go home" },
	{ on = [ "g", "c" ], run = "cd ~/.config",   desc = "Go config" },
	{ on = [ "g", "d" ], run = "cd ~/Downloads", desc = "Go Downloads" },
	{ on = [ "g", "n" ], run = "cd ~/Documents", desc = "Go Documents" },
	{ on = [ "g", "p" ], run = "cd ~/Pictures",  desc = "Go Pictures" },
	{ on = [ "g", "o" ], run = "cd ~/dotfiles",  desc = "Go dotfiles" },
	{ on = [ "g", "w" ], run = "cd ~/Work",      desc = "Go Work" },
	{ on = [ "g", "r" ], run = 'shell -- root="$(git rev-parse --show-toplevel 2>/dev/null)"; [ -n "$root" ] && ya emit cd "$root"', desc = "Go git root" },
	{ on = [ "g", "l" ], run = 'shell --block lazygit', desc = "Open lazygit" },
	{ on = "!", for = "unix", run = 'shell "$SHELL" --block', desc = "Open shell here" },
	{ on = "<C-n>", run = "shell -- dragon-drop -x -i -T %h", desc = "Drag hovered file" },
	{ on = "O", run = "open --interactive", desc = "Open with..." },
	{ on = [ "o", "e" ], run = "open --interactive", desc = "Open with..." },
	{ on = [ "c", "p" ], run = "copy path", desc = "Copy path" },
	{ on = [ "c", "d" ], run = "copy dirname", desc = "Copy dirname" },
	{ on = [ "c", "f" ], run = "copy filename", desc = "Copy filename" },
	{ on = [ "c", "n" ], run = "copy name_without_ext", desc = "Copy name without ext" },
	{ on = [ "y", "i" ], run = 'shell -- mime="$(file -Lb --mime-type %h)"; case "$mime" in image/*) wl-copy --type "$mime" < %h ;; *) exit 1 ;; esac', desc = "Copy image data" },
	{ on = [ "y", "y" ], run = [ 'shell -- for path in %s; do echo "file://$path"; done | wl-copy -t text/uri-list', "yank" ], desc = "Yank file URI" },
]

[tasks]
prepend_keymap = [
	{ on = "q", run = "close", desc = "Close task manager" },
]

[spot]
prepend_keymap = [
	{ on = "q", run = "close", desc = "Close spot" },
]
